# Generated by Django 3.0.4 on 2020-03-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagecategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
