# Generated by Django 3.0.4 on 2020-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_cleaner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cleaner',
        ),
    ]
