# Generated by Django 3.0.4 on 2020-03-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_cleaner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='price',
        ),
    ]
