# Generated by Django 3.0.4 on 2020-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200322_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='garbage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
