# Generated by Django 3.0.4 on 2020-03-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_garbageorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GarbageOrder',
        ),
    ]
