# Generated by Django 3.0.4 on 2020-03-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_delete_garbageorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.IntegerField()),
                ('ordered_garbage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Garbage')),
            ],
        ),
    ]
