# Generated by Django 3.0.1 on 2020-03-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='institution',
            field=models.CharField(default='abc LTD', max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='Name', max_length=255),
        ),
    ]
