# Generated by Django 3.0.4 on 2020-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_kit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(default='+8801', max_length=20)),
                ('payment_method', models.CharField(choices=[('B', 'Bkash'), ('R', 'Rocket'), ('N', 'Nogod'), ('U', 'Upay')], max_length=1)),
                ('transection_no', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
