# Generated by Django 3.0.4 on 2020-04-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compain_and_notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='body',
            new_name='desc',
        ),
    ]
